blog/urls.py
from django.urls import include,re_path
from blog import views
from django.contrib import admin
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('accueil/', views.accueil),
    path('article/<id>/' ,views.lire),
    path('date/',views.date_actuelle),
    path('addition/<int:nombre1>/<int:nombre2>/',views.addition),
    path('caca/', views.caca),
    path('contact/',views.contact,name= 'contact')
]

crepes_bretonnes/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from crepes_bretonnes import views

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls'))
]

blog/models.py
from django.db import models

class Categorie(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom

class Article(models.Model):
    titre =  models.CharField(max_length=100)
    auteur = models.CharField(max_length=42)
    contenu = models.TextField(null=True)
    date = models.DateTimeField(auto_now_add=True, auto_now=False,
        verbose_name="Date de parution")
    categorie = models.ForeignKey('Categorie',on_delete=models.CASCADE)
    def __str__(self):
        return self.titre

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    sujet = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    envoyeur = forms.EmailField(label="Votre adresse mail")
    renvoi = forms.BooleanField(help_text="Cochez si vous souhaitez obtenir une copi",required=False)

blog/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render
from datetime import datetime
from django.shortcuts import render
from blog.models import Article
from blog.forms import ContactForm

def date_actuelle(request):
    return render(request, 'blog/date.html', {'dates':
    datetime.now()})

def addition(request, nombre1, nombre2):
    total = int(nombre1) + int(nombre2)
    # Retourne nombre1, nombre2 et la somme des deux au tpl
    return render(request, 'blog/addition.html', locals())

def home(request):
    """ Exemple de page HTML, non valide pour que l'exemple soit concis """
    text = """<h1>Bienvenue sur mon blog !</h1>
    <p>Les crêpes bretonnes ça tue des mouettes en plein vol !</p>"""
    return HttpResponse(text)
def caca(request):
    """ Exemple de page HTML, non valide pour que l'exemple soit concis """
    text = """<h1>Bienvenue sur mon  !</h1>
    <p>Les crêpes bretonnes ça tue des mouettes en plein vol !</p>"""
    return HttpResponse(text)
def view_article(request, id_article):
    """
    Vue qui affiche un article selon son identifiant (ou ID, ici un numéro)
    Son ID est le second paramètre de la fonction (pour rappel, le premier
    paramètre est TOUJOURS la requête de l'utilisateur)
    """
    text = "Vous avez demandé l'article #{0} !".format(id_article)
    return HttpResponse(text)
def accueil(request):
    """ Afficher tous les articles de notre blog """
    articles = Article.objects.all() # Nous sélectionnons tous nos
    articles
    return render(request, 'blog/accueil.html',
    {'derniers_articles':articles})
    
def lire(request, id):
    """ Afficher un article complet """
    try:
        article = Article.objects.get(id=id)
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'blog/lire.html', {'article': article})



def contact(request):
    if request.method == 'POST': # S'il s'agit d'une requête POST
        form = ContactForm(request.POST) # Nous reprenons les
        if form.is_valid(): # Nous vérifions que les données
        # Ici nous pouvons traiter les données du formulaire
            sujet = form.cleaned_data['sujet']
            message = form.cleaned_data['message']
            envoyeur = form.cleaned_data['envoyeur']
            renvoi = form.cleaned_data['renvoi']
            envoi = True
    else: # Si ce n'est pas du POST, c'est probablement une requête
        form = ContactForm() # Nous créons un formulaire vide
    return render(request, 'blog/contact.html', locals())

crepes_bretonnes/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.http import Http404
from datetime import datetime
from django.shortcuts import render

def home(request):
    request 
    return render(request,'base.html')

blog/templates/blog/accueil.html
<h1>Bienvenue sur le blog des crêpes bretonnes !</h1>
{% for article in derniers_articles %}
    <div class="article">
        <h3>{{ article.titre }}</h3>
        <p>{{ article.contenu|truncatewords_html:80 }}</p>
        
    </div>
{% empty %}
    <p>Aucun article.</p>
{% endfor %}

blog/templates/blog/addition.html
{% load static %}
<img src="{% static 'image.jpg' %}" alt="Mon image" />

<h1>Ma super calculatrice</h1>
<p>{{ nombre1 }} + {{ nombre2 }}, ça fait <strong>{{ total }}</strong> !<br />
Nous pouvons également calculer la somme dans le template : {{ nombre1|add:nombre2 }}.</p>

blog/templates/blog/contact.html
{% if envoi %}Votre message a bien été envoyé !{% endif %}

<form action="{% url 'blog:contact' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

blog/templates/blog/date.html
<h1>Bienvenue sur mon blog</h1>
<p>La date actuelle est : {{ dates }}</p>

blog/templates/blog/lire.html
<h1>{{ article.titre }} <span class="small">dans {{ article.categorie.nom }}</span></h1>
    <p class="infos">Rédigé par {{ article.auteur }}, le {{ article.date|date:"DATE_FORMAT" }}</p>
    <div class="contenu">{{ article.contenu|linebreaks }}</div>

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
<link rel="stylesheet" href="/media/css/style.css" />
<title>Mon blog sur les crêpes bretonnes</title>
</head>
<body>
<header>Crêpes bretonnes</header>
<nav>
{% block nav %}
<ul>
<li><a href="/">Accueil</a></li>
<li><a href="/blog/accueil/">Blog</a></li>
<li><a href="/blog/contact/">Contact</a></li>
</ul>
{% endblock %}
</nav>
<section id="content">
{% block content %}{% endblock %}
</section>
<footer>© Crêpes bretonnes</footer>
</body>
</html>